DROP DATABASE IF EXISTS kleiton;
CREATE DATABASE kleiton;
USE kleiton;

CREATE TABLE macarroes(
id INT PRIMARY KEY AUTO_INCREMENT,
tipo VARCHAR(100),
marca VARCHAR(100),
peso DOUBLE,
aldente BOOLEAN
);
